### ISSUE TITLE
failed to select a version for the requirement `embassy-executor = "^0.1.0"` candidate versions found which didn't match: 0.3.3 location searched: Git repository https://github.com/embassy-rs/embassy required by package `stm32f4xxgpio-embassy v0.1.0 

### ISSUE THREAD

**Issue by Chronic5757** [apollolabsdev/stm32-nucleo-f401re#3]
![image](https://github.com/apollolabsdev/stm32-nucleo-f401re/assets/132540039/8d702295-adf5-44d7-8070-34c6dbecfe1e)
The problem with rust crates is really a headache. Many times I don’t know which foreign version to choose. I completely cloned the project and then this error appeared.

**Comment by apollolabsdev** [comment]
I revised all the examples and updated the configurations in  `Cargo.toml` and `rusttoolchain.toml`. This introduced additional breaking changes in many of the files since some of the interfaces changed as well. I have fixed all except for the PWM example. It still needs some work. I'll open a separate issue for that. 

If you clone, things should be fine now.

Unfortunately, this is expected to keep on happening until the project becomes more stable. It's been a year since these files were released and haven't been updated since.
