### ISSUE TITLE
External Clock Setup Bug

### ISSUE THREAD

**Issue by eroomde** [apollolabsdev/stm32-nucleo-f401re#5]
https://github.com/apollolabsdev/stm32-nucleo-f401re/blob/c586a50d609aa8c1d90e113277d4e5bb99ae81d6/PAC%20Examples/sys_clocks/src/main.rs#L18C45-L18C45

Isn't this ready signal bit going to be 0 initially, in which case the busy-wait won't run and execution will pass straight to the next line (without the clock being ready), _or_ the clock will be ready, in which case the while test will evaluate to 1, in which case it will get stuck in the busy-wait forever?

**Comment by apollolabsdev** [comment]
That is correct, the busy wait logic is flawed, and it should be inverted. Although at the time I tested the code and it worked, I have to dig into why since the HSE is not actually signalling a ready. My feeling is that this might have something to do with the clock bypass but I have to confirm. 

It's been a while away from this code and its hardware, so I have to dig it up to figure out what's going on 😄

I'll update my findings (and the code) as soon I have answers.

**Comment by apollolabsdev** [comment]
An update: I got to test this and there's some strange behavior. 

Running the code in debug mode the line does not proceed with the flawed logic (expected behaviour).

Running the code without debug mode, it didn't seem to matter what the logic was. Execution passes to the next line regardless of the logic. I figure that's why I overlooked this.

I'm going to try to investigate a bit more.

**Comment by apollolabsdev** [comment]
The issue has been resolved and the code updated accordingly. 

Based on hardware behavior, in both cases, and unless the HSE is never ready, the application won't get stuck in a busy wait forever. This is because the ready flag defaults to low/false. However, in the case of the adjusted (correct) logic, it takes 17 cycles before it exits the loop after the ready flag is asserted. This was tested on the Nucleo-STMF401RE board.
